/** After Effects 用 ExtendScript (.jsx) 生成(スペック §8)。
 *  生成コードは ES3 のみ(var / 文字列連結 / \uXXXX)。エフェクトやプロパティは
 *  matchName で参照し、日本語版 AE でもそのまま動くようにする。 */
import { resampleEnvelopeToFps } from "../envelope.js";
import { fpsValue, timeToFrame } from "../timebase.js";
import type { ExportContext, Marker } from "../types.js";
import { escapeJsString, selectMarkers } from "./helpers.js";

/** AE のマーカー/レイヤーラベル色番号(1-16)への種別マップ */
const TYPE_TO_AE_LABEL: Record<Marker["type"], number> = {
  section: 9,  // 赤系
  bar: 5,      // シアン系
  beat: 14,    // 淡青
  hit: 2,      // 黄
  silence: 8,  // 灰青
  custom: 10,  // 紫
};

const TYPE_PRIORITY: Record<Marker["type"], number> = {
  section: 0, bar: 1, beat: 2, hit: 3, silence: 4, custom: 5,
};

function fpsLiteral(ctx: ExportContext): string {
  return ctx.fps.den === 1 ? String(ctx.fps.num) : `${ctx.fps.num} / ${ctx.fps.den}`;
}

function numLit(n: number): string {
  return Number.isInteger(n) ? String(n) : String(Math.round(n * 1e6) / 1e6);
}

export function exportAeJsx(markers: Marker[], ctx: ExportContext): string {
  // 同一フレームに落ちるマーカーは種別優先度の高い1つだけ(AEは同時刻を上書きするため)。
  // 丸めで同フレームに衝突する異なるtimeSecのマーカーも正しく優先度判定できるよう、
  // フレーム番号を先に確定してから (frame, 優先度) でソートする(レビュー修正)。
  const framed = selectMarkers(markers, ctx.include)
    .map((m) => ({ m, frame: timeToFrame(m.timeSec, ctx.fps, ctx.rounding) }))
    .sort((a, b) => a.frame - b.frame || TYPE_PRIORITY[a.m.type] - TYPE_PRIORITY[b.m.type]);

  const seen = new Set<number>();
  const rows: string[] = [];
  for (const { m, frame } of framed) {
    if (seen.has(frame)) continue;
    seen.add(frame);
    const dur = m.meta?.durationSec ?? 0;
    rows.push(
      `BM_MARKERS.push([${numLit(m.timeSec)}, '${escapeJsString(m.label)}', ` +
      `${numLit(dur)}, ${TYPE_TO_AE_LABEL[m.type]}]);`,
    );
  }

  // エンベロープ(0-100スケールでスライダーへ)
  let envDecl = "";
  let envApply = "";
  if (ctx.envelopes) {
    const bands = ["total", "low", "mid", "high"] as const;
    const series = bands.map((b) =>
      resampleEnvelopeToFps(ctx.envelopes![b], ctx.envelopes!.sampleRateHz, ctx.fps, ctx.audioDurationSec)
        .map((v) => Math.round(v * 1000) / 10), // 0-100, 小数1桁
    );
    const n = series[0]!.length;
    envDecl =
      `var BM_ENV_N = ${n};\n` +
      bands.map((b, i) => `var BM_ENV_${b} = [${series[i]!.join(",")}];`).join("\n") + "\n";
    envApply = [
      "  var envLayer = comp.layers.addNull(DURATION);",
      "  envLayer.name = 'BM_Envelopes';",
      "  var envTimes = [];",
      "  for (var ti = 0; ti < BM_ENV_N; ti++) { envTimes.push(ti / FPS); }",
      "  var BM_BANDS = [['total', BM_ENV_total], ['low', BM_ENV_low], ['mid', BM_ENV_mid], ['high', BM_ENV_high]];",
      "  for (var bi = 0; bi < BM_BANDS.length; bi++) {",
      "    var fx = envLayer.property('ADBE Effect Parade').addProperty('ADBE Slider Control');",
      "    fx.name = 'BM_' + BM_BANDS[bi][0];",
      "    fx.property('ADBE Slider Control-0001').setValuesAtTimes(envTimes, BM_BANDS[bi][1]);",
      "  }",
    ].join("\n");
  }

  const compName = escapeJsString(`${ctx.baseName}_BeatMarks`);
  const audioFile = escapeJsString(ctx.audioFileName);
  const info = escapeJsString(`BPM ${ctx.bpmLabel} / KEY ${ctx.keyLabel}`);

  return [
    `// BeatMarks export for After Effects (generated by BeatMarks 0.1.0)`,
    `// fps=${fpsValue(ctx.fps).toFixed(3)} rounding=${ctx.rounding}`,
    `(function () {`,
    `  var USE_LAYER_MARKERS = false; // set true to put markers on the audio layer`,
    `  var AUDIO_FILE = '${audioFile}'; // picked via dialog if missing`,
    ``,
    `  var FPS = ${fpsLiteral(ctx)};`,
    `  var DURATION = ${numLit(ctx.audioDurationSec)};`,
    ``,
    `  var BM_MARKERS = [];`,
    rows.map((r) => `  ${r}`).join("\n"),
    envDecl ? envDecl.split("\n").map((l) => (l ? `  ${l}` : l)).join("\n") : `  // (envelopes: none)`,
    ``,
    `  app.beginUndoGroup('BeatMarks Import');`,
    `  var comp = app.project.items.addComp('${compName}', 1920, 1080, 1.0, DURATION, FPS);`,
    `  comp.comment = '${info}';`,
    ``,
    `  var audioLayer = null;`,
    `  try {`,
    `    var f = File(AUDIO_FILE);`,
    `    if (!f.exists) { f = File.openDialog('BeatMarks: \\u97f3\\u58f0\\u30d5\\u30a1\\u30a4\\u30eb\\u3092\\u9078\\u629e (' + AUDIO_FILE + ')'); }`,
    `    if (f && f.exists) {`,
    `      var footage = app.project.importFile(new ImportOptions(f));`,
    `      audioLayer = comp.layers.add(footage);`,
    `    }`,
    `  } catch (eImport) {}`,
    ``,
    `  var target = comp.markerProperty;`,
    `  if (USE_LAYER_MARKERS && audioLayer !== null) { target = audioLayer.marker; }`,
    `  for (var i = 0; i < BM_MARKERS.length; i++) {`,
    `    var row = BM_MARKERS[i];`,
    `    var mv = new MarkerValue(row[1]);`,
    `    if (row[2] > 0) { mv.duration = row[2]; }`,
    `    try { mv.label = row[3]; } catch (eLabel) {} // AE 2019+`,
    `    target.setValueAtTime(row[0], mv);`,
    `  }`,
    envApply ? envApply : `  // (no envelope layer)`,
    `  app.endUndoGroup();`,
    `})();`,
    ``,
  ].join("\n");
}
