/** Blender 用スクリプト。テキストエディタで開いて実行すると fps 設定+
 *  タイムラインマーカーを生成する(スペック §8)。 */
import { timeToFrame } from "../timebase.js";
import type { ExportContext, Marker } from "../types.js";
import { selectMarkers } from "./helpers.js";

function pyString(s: string): string {
  let out = "";
  for (const ch of s) {
    const code = ch.codePointAt(0)!;
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (code < 0x20) out += `\\x${code.toString(16).padStart(2, "0")}`;
    else out += ch; // Python3 ソースは UTF-8 なので非ASCIIはそのままでよい
  }
  return `"${out}"`;
}

export function exportBlenderPy(markers: Marker[], ctx: ExportContext): string {
  const sel = selectMarkers(markers, ctx.include);
  const fpsInt = Math.ceil(ctx.fps.num / ctx.fps.den);
  const fpsBase = ctx.fps.den === 1001 ? "1.001" : "1.0";
  const endFrame = timeToFrame(ctx.audioDurationSec, ctx.fps, "floor");

  const markerLines = sel.map((m) => {
    const frame = timeToFrame(m.timeSec, ctx.fps, ctx.rounding);
    return `scene.timeline_markers.new(${pyString(m.label)}, frame=${frame})`;
  });

  // コメント行は生のPythonソースに連結されるため、改行が混入すると
  // 後続行を注入されうる(bpmLabel/keyLabelはUI組み立て値だが念のため潰す)。
  const info = `BPM ${ctx.bpmLabel} / KEY ${ctx.keyLabel}`.replace(/[\r\n]+/g, " ");

  return [
    `# BeatMarks export for Blender (generated by BeatMarks 0.1.0)`,
    `# ${info}`,
    `import bpy`,
    ``,
    `ADD_SOUND = False  # True にすると VSE に音声ストリップを配置`,
    `AUDIO_FILE = ${pyString(ctx.audioFileName)}`,
    ``,
    `scene = bpy.context.scene`,
    `scene.render.fps = ${fpsInt}`,
    `scene.render.fps_base = ${fpsBase}`,
    `scene.frame_start = 0`,
    `scene.frame_end = ${endFrame}`,
    ``,
    ...markerLines,
    ``,
    `if ADD_SOUND:`,
    `    if not scene.sequence_editor:`,
    `        scene.sequence_editor_create()`,
    `    scene.sequence_editor.sequences.new_sound("BeatMarks Audio", AUDIO_FILE, 1, 0)`,
    ``,
    `print("BeatMarks: %d markers" % ${sel.length})`,
    ``,
  ].join("\n");
}
