/** 全UI文言(スペック §7: 日本語MVP、将来英語化のため定数分離)。
 *  画面/機能ごとにネストし、コンポーネントは STRINGS.xxx を参照する。 */
export const STRINGS = {
  app: {
    name: "BeatMarks",
    extractedSuffix: "音声抽出済み",
    analyzeDone: "解析完了",
    engineStandard: "標準エンジン",
  },
  drop: {
    prompt: "音声・動画ファイルをここにドロップ",
    hint: "対応: mp4 / mov / wav / mp3 ほか(ffmpeg が扱える形式)",
    loadFailed: "ファイルの読み込みに失敗しました",
  },
  inputConfig: {
    title: "入力設定(複数トラック検出)",
    mixMode: "選択トラックを2mixに統合",
    multitrackMode: "マルチトラックとして読み込む(トラックごとに解析)",
    stereoSplit: "L/R を個別ソースとして解析",
    start: "解析開始",
  },
  analyzing: {
    title: "解析中…",
    preparing: "準備中",
    cancel: "キャンセル",
    cancelNote: "キャンセルは解析開始後に効きます(抽出フェーズ中は完了を待ちます)",
    extracting: "音声を抽出中…",
  },
  error: {
    title: "エラー",
    back: "戻る",
    extractFailed: "このファイルから音声を抽出できませんでした。対応形式か、破損・DRM保護がないかを確認してください。",
    analyzeFailed: "解析に失敗しました",
    unknown: "不明なエラーが発生しました",
  },
  transport: {
    prev: "⏮",
    prevTitle: "先頭へ",
    play: "▶",
    pause: "⏸",
    loop: "🔁 ループ",
    setA: "A",
    setB: "B",
    confirmGroup: "確認",
    metronome: "🔔 メトロノーム",
    tapTempo: "タップテンポ",
    addGroup: "追加",
    addMarker: "◈ 手動マーカー",
    zoom: "ズーム",
    fpsDisplaySuffix: "fps 表示",
    secDisplaySuffix: "s表示",
    cycleUnitTitle: "クリックで表示単位を切替(秒 / フレーム / TC / 小節.拍)",
  },
  grid: {
    bpm: "BPM",
    fixed: "固定",
    variable: "可変テンポ",
    half: "½",
    double: "×2",
    offset: "グリッドオフセット",
    minus10: "−10ms",
    minus1: "−1ms",
    plus1: "+1ms",
    plus10: "+10ms",
    timeSig: "拍子",
    downbeatLeft: "1拍目 ←",
    downbeatRight: "→",
    downbeatTitle: "小節頭を1拍ずらす",
    anchorSet: "アンカー設定",
    anchorClear: "アンカー解除",
    key: "KEY",
    confidence: "信頼度",
    lowConfidence: "信頼度低",
    perSectionKeyPrefix: "セクション別: ",
    metronomeHint: "メトロノーム音を重ねて再生し、グリッドのズレを耳で確認 → オフセットで微調整",
    undo: "取り消し",
    redo: "やり直し",
  },
  overview: {
    hint: "曲全体。ドラッグで表示範囲を移動",
  },
  section: {
    barsSuffix: "小節",
    editHint: "境界ドラッグで移動 / ダブルクリックでリネーム / ×ボタンで削除",
    addAtPlayhead: "＋境界(再生位置)",
    defaultLabel: "新規セクション",
    rename: "リネーム",
    delete: "削除",
    deleteGlyph: "×",
  },
  hitLane: {
    tag: "ヒット検出レーン",
    low: "低域",
    mid: "中域",
    high: "高域",
    sensitivity: "感度",
    instantHint: "しきい値は再解析なしで即反映",
  },
  markerTable: {
    title: "マーカー一覧",
    countTemplate: (total: number, shown: number) => `全 ${total} 件(表示 ${shown} 件)`,
    filterSection: "セクション",
    filterBar: "小節",
    filterBeat: "拍",
    filterHit: "ヒット",
    filterSilence: "静寂",
    filterCustom: "手動",
    showDeletedLabel: "削除済み",
    showDeletedAria: "削除済みを表示",
    addButton: "＋追加",
    colType: "種別",
    colLabel: "ラベル",
    colTimecode: "タイムコード",
    colFrame: "フレーム",
    colSeconds: "秒",
    colTrack: "ソース",
    colSource: "出所",
    colOp: "操作",
    srcAuto: "自動",
    srcUser: "手動",
    crossSource: "全ソース横断",
    renameGlyph: "✎",
    renameAria: (id: string) => `リネーム ${id}`,
    deleteGlyph: "🗑",
    deleteAria: (id: string) => `削除 ${id}`,
    restoreButton: "復元",
    restoreAria: (id: string) => `復元 ${id}`,
    labelEditAria: (id: string) => `ラベル編集 ${id}`,
    hitTypeTemplate: (band: "low" | "mid" | "high") =>
      `ヒット（${band === "low" ? "低" : band === "mid" ? "中" : "高"}）`,
    strengthTemplate: (v: number) => `強度 ${v.toFixed(2)}`,
  },
  markerType: {
    beat: "拍",
    bar: "小節",
    section: "セクション",
    hit: "ヒット",
    silence: "静寂",
    custom: "手動",
  },
  timeUnit: {
    sec: "秒",
    frame: "フレーム",
    tc: "TC",
    barBeat: "小節.拍",
  },
  snap: {
    beat: "拍",
    bar: "小節",
    frame: "フレーム",
    none: "なし",
    label: "スナップ",
  },
  exportPanel: {
    title: "書き出し",
    fps: "フレームレート",
    rounding: "丸め",
    roundNearest: "最近傍",
    roundFloor: "切り捨て",
    includeLabel: "含めるマーカー:",
    incSection: "セクション",
    incBar: "小節",
    incBeat: "拍",
    incHit: "ヒット(低のみ)",
    incCustom: "手動",
    incEnvelope: "エンベロープ",
    targetsLabel: "書き出し先(複数可):",
    runTemplate: (n: number) => `⬇ 書き出し(${n}ファイル)`,
    aeNote: "AE: コンポマーカー+エンベロープをヌルに焼き込み",
    phase2Badge: "Phase2",
    doneTemplate: (n: number) => `${n} ファイルを書き出しました`,
    failedTemplate: (n: number) => `${n} ファイルの書き出しに失敗しました`,
    retry: "リトライ",
    changeDir: "場所を変更",
    noTarget: "書き出し先を1つ以上選んでください",
  },
  menu: {
    open: "開く…",
    save: "保存",
    saveAs: "別名で保存…",
    recent: "最近使ったファイル",
    hashMismatchTitle: "音声が変更されています",
    hashMismatch: "プロジェクト保存後に元の音声ファイルが変更された可能性があります。続行しますか?",
    continue: "続行",
    abort: "中止",
    mediaMissing: "元の音声ファイルが見つかりません",
  },
  shortcuts: {
    playPause: "再生/停止",
    marker: "マーカー追加",
    beatSeek: "拍単位シーク",
    undo: "取り消し",
    lanes: "レーン表示切替",
  },
} as const;

export type Strings = typeof STRINGS;
